import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';
const{chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({headless:true});const page=await browser.newPage();const base=process.env.TEST_BASE||'http://127.0.0.1:4173';const errors=[],posts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')posts.push(r.url());});
try{
 await page.goto(base+'/절차/간편.html?entry=situation');await page.locator('#story-text').fill('처음 적은 내용');await page.getByRole('button',{name:'있었던 일 추가 (최대 10개)',exact:true}).click();await page.locator('#story-text-1').fill('두 번째 일');await page.locator('#story-date-1').fill('2026-02-30');assert.equal(await page.locator('#story-text').inputValue(),'처음 적은 내용');
 await page.getByRole('button',{name:'정리한 내용 확인하기'}).click();const row=page.locator('.review-item').filter({has:page.locator('#story-text')});await row.locator('summary').click();await page.locator('#story-text').fill('고친 내용');assert.ok((await row.locator('summary').innerText()).includes('고친 내용'));assert.ok(!(await row.locator('summary').innerText()).includes('처음 적은 내용'));
 await page.locator('#story-check').check();await page.getByRole('button',{name:'상담 준비자료 만들기'}).click();assert.ok((await page.locator('#screen').textContent()).includes('달력'));const dl=page.waitForEvent('download');await page.getByRole('button',{name:'준비자료 내려받기 (.txt)'}).click();const text=await readFile(await(await dl).path(),'utf8');assert.ok(text.includes('고친 내용'));assert.ok(text.includes('두 번째 일'));assert.ok(text.includes('2026-02-30'));
 await page.goto(base+'/절차/간편.html?entry=document');await page.getByText('파일 대신 글을 붙여넣을게요').click();await page.locator('#paste').fill('내용증명\n확인할 내용입니다.');await page.getByRole('button',{name:'이 내용 확인하기',exact:true}).click();assert.ok((await page.locator('#screen').textContent()).includes('내용증명'));assert.equal(await page.getByText('채무자',{exact:true}).count(),0);
 await page.locator('#facts-checked').check();await page.getByRole('button',{name:'이 내용으로 계속'}).click();await page.getByRole('button',{name:'정리한 내용 확인하기'}).click();await page.getByText('앞에서 확인한 서류 보기',{exact:true}).click();await page.getByRole('button',{name:'서류 내용 수정'}).click();await page.getByRole('button',{name:'수정',exact:true}).first().click();await page.getByRole('textbox',{name:'문서 제목 수정'}).fill('출석요구서');await page.getByRole('button',{name:'수정 반영'}).click();await page.locator('#facts-checked').check();await page.getByRole('button',{name:'이 내용으로 계속'}).click();assert.ok(await page.getByRole('heading',{name:'내가 적은 내용, 맞나요?'}).isVisible());
 await page.goto(base+'/절차/간편.html?entry=document');await page.getByText('파일 대신 글을 붙여넣을게요').click();await page.locator('#paste').fill('남겨둘 붙여넣기');await page.locator('#upload').setInputFiles({name:'bad.pdf',mimeType:'application/pdf',buffer:Buffer.from('bad')});await page.getByText('읽지 못했습니다.',{exact:false}).waitFor();await page.getByText('파일 대신 글을 붙여넣을게요').click();assert.equal(await page.locator('#paste').inputValue(),'남겨둘 붙여넣기');
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'입력 지우기',exact:true}).click();await page.goBack();assert.equal(await page.locator('#draft-preview').count(),0);
 await page.goto(base+'/절차/간편.html?entry=situation');await page.locator('#story-text').fill('첫 번째 일은 유지합니다.');await page.getByRole('button',{name:'있었던 일 추가 (최대 10개)',exact:true}).click();await page.locator('#story-text-1').fill('지울지 확인할 항목');page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'이 항목 지우기'}).click();assert.equal(await page.locator('#story-text-1').inputValue(),'지울지 확인할 항목');page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'이 항목 지우기'}).click();assert.equal(await page.locator('#story-text-1').count(),0);assert.equal(await page.locator('#story-text').inputValue(),'첫 번째 일은 유지합니다.');
 await page.getByRole('button',{name:'있었던 일 추가 (최대 10개)',exact:true}).click();await page.locator('#story-text-1').fill('두 번째 일은 날짜가 기억나지 않습니다.');await page.getByRole('button',{name:'정리한 내용 확인하기'}).click();
 for(const width of [320,375,768,1280]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}await page.setViewportSize({width:375,height:900});await page.screenshot({path:'/private/tmp/journey-followup-review.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(posts,[]);console.log('PASS: live summary, multiple events/download, general document labels, return to review, paste survives file error, reset/history, deletion confirmation');
}finally{await browser.close();}
