export const formFields=[['caseNumber','사건번호'],['court','지급명령 발령 법원'],['creditor','채권자'],['debtor','채무자'],['address','채무자 주소'],['contact','연락처'],['received','송달받은 날'],['written','작성일']];
export function seed(intake={},reason=''){return {...Object.fromEntries(formFields.map(([k])=>[k,intake[k]||''])),reason,scope:'',partial:''};}
export function missing(d){const dates=['received','written'].filter(k=>d[k]?.trim()).filter(k=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(d[k]))return true;const date=new Date(d[k]+'T00:00:00Z');return !Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==d[k];}).map(k=>(k==='received'?'송달받은 날':'작성일')+' — 정확한 달력 날짜(YYYY-MM-DD) 확인');return [...formFields.filter(([k])=>!d[k]?.trim()).map(([,label])=>label),...dates,...(!['all','partial'].includes(d.scope)?['이의 범위']:[]),...(d.scope==='partial'&&!d.partial?.trim()?['일부 이의의 구체적인 범위']:[])];}
export function documentText(d){
 const v=k=>d[k]?.trim()||'[미확인 — 직접 확인 필요]';
 const scope=d.scope==='all'?'전부':d.scope==='partial'?`일부 (${v('partial')})`:'[이의 범위 미선택]';
 return `검토용 초안 — 공식 양식 대조 및 제출 전 확인 필요\n\n지급명령에 대한 이의신청서\n\n사건: ${v('caseNumber')} 지급명령\n채권자: ${v('creditor')}\n채무자: ${v('debtor')}\n주소: ${v('address')}\n연락처: ${v('contact')}\n\n위 사건의 지급명령을 송달받은 날: ${v('received')}\n\n채무자는 위 지급명령의 ${scope}에 대하여 이의를 신청합니다.\n\n이의 이유 (사용자가 작성한 내용):\n${d.reason?.trim()||'[미기재]'}\n\n작성일: ${v('written')}\n채무자: ${v('debtor')} (서명 또는 날인: 직접 하세요)\n\n${v('court')} 귀중\n\n── 제출 전 확인 목록 (신청서 본문과 구분) ──\n${missing(d).length?'미확인 항목: '+missing(d).join(', '):'기본 기재칸은 채웠습니다. 사실·법률 검토가 완료됐다는 뜻은 아닙니다.'}\n실제 송달일과 제출기한, 이의 범위, 당사자와 사건번호, 관할 법원, 공식 양식, 서명과 접수 확인 방법을 확인하세요.\n사건 경위와 상대방 주장을 자동으로 사실로 인정하지 않았으며, 기한·법적 적합성·제출 가능 여부를 판단하지 않았습니다.\n이 파일은 검토용입니다. 확인 목록과 미확인 표시가 남은 채 그대로 제출하지 마세요.`;
}
export function documentHTML(d){const escaped=documentText(d).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return `<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>지급명령 이의신청 검토용 초안</title><style>body{max-width:800px;margin:32px auto;padding:20px;font:16px/1.8 system-ui}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:inherit}@media print{body{margin:0;padding:0}}</style><pre>${escaped}</pre></html>`;}
