import {blank} from './writing-model.mjs';
import {mountJourney} from './journey.mjs';
import {extract} from './extract.mjs';
import {seed,missing,documentText,documentHTML} from './payment-draft.mjs';
const $=id=>document.getElementById(id);
const labels={title:'문서 제목',caseNumber:'사건번호',court:'보낸 법원',creditor:'채권자',debtor:'채무자',request:'문서의 요구',deadlineText:'기한 안내'};
const keys=Object.keys(labels);let story=blank(),resumeReview=false;
const entry=new URLSearchParams(location.search).get('entry');
let stage=entry==='document'?0:entry==='situation'?4:-1,source='',values={},candidates={},form=seed(),checked=false,role='',goal='',generation=0,controller=null,worker=null,busy=false;
const e=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function button(text,action,primary=false){const b=e('button',text);if(primary)b.className='primary';b.onclick=action;return b;}
function go(next,push=true){if(next===1&&stage===5)resumeReview=true;if(next===3&&(role!=='debtor'||goal!=='prepare'||values.title?.replace(/\s/g,'')!=='지급명령'))next=2;if(next===6&&!story.confirmed)next=5;if(next===5&&!story.events[0].text.trim()&&!story.intake)next=4;stage=next;checked=false;if(push)history.pushState({simple:stage},'',location.href);render();window.scrollTo(0,0);$('screen').querySelector('h1')?.focus();}
function title(text,description){const h=e('h1',text);h.tabIndex=-1;$('screen').append(h,e('p',description));$('screen').lastChild.className='intro';}
function input(container,key,label,value,onChange,large=false){const l=e('label',label),i=e(large?'textarea':'input');i.id='f-'+key;l.htmlFor=i.id;i.value=value||'';i.maxLength=1500;i.oninput=()=>onChange(i.value);container.append(l,i);return i;}
function cancel(){generation++;controller?.abort();controller=null;if(worker){void worker.terminate().catch(()=>{});worker=null;}busy=false;}
async function ocr(image,signal){const local=await Tesseract.createWorker('kor',1,{workerPath:new URL('ocr/worker.min.js',import.meta.url).href,corePath:new URL('ocr/tesseract-core-simd.wasm.js',import.meta.url).href,langPath:new URL('ocr',import.meta.url).href});if(signal.aborted){await local.terminate();throw Error('읽기를 취소했습니다.');}worker=local;try{return (await local.recognize(image)).data.text||'';}finally{await local.terminate().catch(()=>{});if(worker===local)worker=null;}}
function load(text){if(!text.trim()||text.length>20000)throw Error('1~20,000자의 문서 내용을 넣어 주세요.');story=blank();resumeReview=false;source=text;candidates=extract(source);values=Object.fromEntries(keys.map(k=>[k,candidates[k]?.value||'']));form=seed(values);role='';goal='';go(1);}
async function fileRead(file){if(!file)return;if(file.size>20*1024*1024){$('status').textContent='20MB 이하 파일을 넣어 주세요.';return;}cancel();const token=generation;controller=new AbortController();const activeController=controller;const signal=activeController.signal;busy=true;render();$('status').textContent='기기 안에서 읽는 중입니다. 스캔 문서는 시간이 걸릴 수 있습니다.';const timer=setTimeout(()=>activeController.abort(),120000);const abort=()=>{if(token===generation){cancel();render();$('status').textContent='읽기가 중단됐습니다. 글 붙여넣기로도 계속할 수 있습니다.';}};signal.addEventListener('abort',abort,{once:true});let url;try{let text;if(file.type==='application/pdf'||/\.pdf$/i.test(file.name)){const {readPdf}=await import('./pdf/reader.mjs');const out=await readPdf(file,{signal,ocr:img=>ocr(img,signal)});text=out.text;}else if(/^image\/(png|jpeg|webp)$/.test(file.type)){url=URL.createObjectURL(file);text=await ocr(url,signal);}else throw Error('PDF 또는 JPG·PNG·WebP 사진을 넣어 주세요.');if(token!==generation||signal.aborted)return;busy=false;load(text);}catch(error){if(token===generation){busy=false;render();$('status').textContent='읽지 못했습니다. '+error.message;}}finally{clearTimeout(timer);signal.removeEventListener('abort',abort);if(url)URL.revokeObjectURL(url);}}
function render(){const host=$('screen');host.replaceChildren();$('status').textContent='';$('back').hidden=stage===-1;$('step').textContent=stage<0?'시작':{0:'서류 넣기',1:'내용 확인',2:'필요한 선택',3:'작성본 확인',4:'상황 정리',5:'내용 검토',6:'준비자료'}[stage];
 if(stage===-1){title('어디서부터 해야 할지, 하나씩 정리해요.','받은 서류나 기억나는 일에서 시작하세요.');const choices=e('div');choices.className='entry-choices';choices.append(button('받은 서류가 있어요',()=>go(0),true),button('어떤 일인지 설명할게요',()=>go(4)));host.append(choices,e('p','사진·PDF·직접 입력을 지원합니다. 이 화면의 파일과 입력은 서버로 보내지 않습니다. 새로고침하면 입력이 사라집니다.'));host.lastChild.className='hint';const link=e('a','서식만 찾기');link.href='/#forms';host.append(link);}
 if(stage>=4)mountJourney(host,{stage,data:story,go});
 if(stage===0){title('받은 서류를 확인해요.','사진·PDF·글에서 읽은 내용을 직접 대조하고 준비자료로 정리합니다.');const panel=e('div');panel.className='panel';panel.append(e('h2','받은 서류를 넣어 주세요'));const file=e('input');file.type='file';file.id='upload';file.accept='.pdf,.jpg,.jpeg,.png,.webp';file.hidden=true;file.onchange=()=>fileRead(file.files[0]);const upload=button(busy?'읽는 중…':'사진 또는 PDF 선택',()=>file.click(),true);upload.disabled=busy;panel.append(file,upload,e('p','최대 20MB · PDF 10쪽. 사진·내용은 서버로 보내지 않습니다.'));panel.lastChild.className='hint';if(busy)panel.append(button('읽기 취소',()=>{cancel();render();}));host.append(panel);const paste=e('details');paste.append(e('summary','파일 대신 글을 붙여넣을게요'));const area=e('textarea');area.id='paste';area.maxLength=20000;area.setAttribute('aria-label','서류 내용');paste.append(area,button('이 내용 확인하기',()=>{try{cancel();load(area.value);}catch(err){$('status').textContent=err.message;}}));host.append(paste);const sample=button('가상 문서로 먼저 체험하기',()=>{cancel();load('서울중앙지방법원\n지급명령\n사건 2026차전12345\n채권자 : 예시상사\n채무자 : 예시사용자\n채무자는 채권자에게 100만원을 지급하라.\n송달받은 날부터 2주 이내 이의신청을 할 수 있습니다.\n[화면 체험을 위한 가상 문서입니다.]');});sample.className='text-button';sample.disabled=busy;host.append(sample,e('p','입력은 자동 저장하지 않습니다. 새로고침하거나 닫기 전에 필요한 작성본을 내려받으세요.'));host.lastChild.className='hint quiet';}
 if(stage===1){title('서류에서 이렇게 읽었습니다.','틀린 곳만 수정하세요. 읽은 내용은 추정이며, 상대방의 주장이 사실로 확인됐다는 뜻은 아닙니다.');const rows=e('div');host.append(rows);const original=e('details');original.className='no-print';const pre=e('pre',source);pre.className='source';original.append(e('summary','읽은 원문과 추출 근거 보기'),pre);
  for(const key of keys){const row=e('div');row.className='summary-row';row.append(e('strong',labels[key]));const value=e('div',values[key]||(candidates[key]?.ambiguous?'여러 값이 있어 확인 필요':'읽지 못함 · 확인 필요'));value.className='value';const edit=button('수정',()=>{const box=e('textarea');box.setAttribute('aria-label',labels[key]+' 수정');box.value=values[key];box.maxLength=1500;box.oninput=()=>{checked=false;next.disabled=true;check.checked=false;};value.replaceChildren(box,button('수정 반영',()=>{values[key]=box.value;form[key]=box.value;story.confirmed=false;if(story.intake){story.intake={...values};story.document=values.title;}checked=false;render();}));box.focus();});edit.className='text-button';row.append(value,edit);if(candidates[key]?.quote){const evidence=button('근거',()=>{original.open=true;pre.replaceChildren(document.createTextNode(source.slice(0,candidates[key].start)));const mark=e('mark',source.slice(candidates[key].start,candidates[key].end));pre.append(mark,document.createTextNode(source.slice(candidates[key].end)));mark.scrollIntoView({block:'center'});});evidence.className='text-button';value.append(e('br'),evidence);}rows.append(row);}
  host.append(original);const label=e('label');label.className='check';const check=e('input');check.type='checkbox';check.id='facts-checked';label.append(check,document.createTextNode('표시된 내용을 원본과 대조했습니다. 모르는 항목은 미확인으로 남깁니다.'));const next=button('이 내용으로 계속',()=>{if(!checked)return;story.intake={...values};story.document=values.title;story.confirmed=false;const destination=resumeReview?5:4;resumeReview=false;go(destination);},true);next.disabled=true;check.onchange=()=>{checked=check.checked;next.disabled=!checked;};host.append(label,next);if(values.title.replace(/\s/g,'')==='지급명령'){const extra=e('details');extra.append(e('summary','지급명령 작성 시안도 찾고 있나요?'),e('p','법률 검수가 완료된 제출 서비스가 아닙니다. 직접 역할과 이의 범위를 선택해 검토용 작성본을 준비하는 기존 시안입니다.'));extra.append(button('지급명령 작성 시안 열기',()=>{if(!checked){$('status').textContent='먼저 원본과 대조했는지 확인해 주세요.';return;}go(2);}));host.append(extra);}}
 if(stage===2){title('어떤 도움을 원하시나요?','법적 대응은 자동으로 선택하지 않습니다. 모르면 확인할 사항부터 정리할 수 있습니다.');const opts=e('div');opts.className='options';for(const [v,t] of [['prepare','지급명령에 이의신청할 작성본을 준비할게요'],['help','내 역할이나 대응 방법부터 확인하고 싶어요']]){const l=e('label');const r=e('input');r.type='radio';r.name='goal';r.value=v;r.checked=goal===v;r.onchange=()=>{goal=v;render();};l.append(r,document.createTextNode(t));opts.append(l);}host.append(opts);
  if(goal==='help'){const p=e('div');p.className='panel';p.append(e('h2','먼저 이 세 가지를 확인하세요'),e('p','① 문서에 적힌 본인의 역할 ② 실제 송달받은 날 ③ 현재 사건 상태와 가능한 대응'));const link=e('a','대한법률구조공단 상담 안내');link.href='https://www.klac.or.kr';link.target='_blank';link.rel='noopener';p.append(link,e('p','받은 문서 전체와 송달 봉투·전자송달 내역을 준비하세요. 기한이 임박했다면 발령 법원에 즉시 확인하세요.'));host.append(p);}
  if(goal==='prepare'){const l=e('label','문서의 ‘채무자’가 본인인가요?');l.htmlFor='role';const select=e('select');select.id='role';for(const [v,t] of [['','선택해 주세요'],['debtor','네, 본인입니다'],['other','아니요 / 모르겠어요']]){const o=e('option',t);o.value=v;select.append(o);}select.value=role;select.onchange=()=>{role=select.value;render();};host.append(l,select);if(role==='other'){host.append(e('p','이 작성본을 바로 만들지 마세요. 위에서 ‘대응 방법부터 확인’을 선택해 확인할 사항을 보세요.'));}
   if(role==='debtor'){const group=e('div');group.className='panel';group.append(e('h2','작성에 필요한 선택'));const scopeLabel=e('label','어느 범위에 이의하나요?');scopeLabel.htmlFor='scope';const scope=e('select');scope.id='scope';for(const [v,t] of [['','아직 확인하지 못함'],['all','전부'],['partial','일부']]){const o=e('option',t);o.value=v;scope.append(o);}scope.value=form.scope;scope.onchange=()=>{form.scope=scope.value;render();};group.append(scopeLabel,scope);if(form.scope==='partial')input(group,'partial','이의하는 부분',form.partial,v=>form.partial=v,true);input(group,'received','실제 송달받은 날 (모르면 비워두세요)',form.received,v=>form.received=v);group.append(e('p','문서 작성일과 다를 수 있습니다. 마감일은 이 시안에서 계산하지 않습니다.'));group.lastChild.className='hint';const optional=e('details');optional.append(e('summary','주소·연락처·작성일·이유 추가 (나중에 보완 가능)'));for(const [k,label] of [['address','주소'],['contact','연락처'],['written','작성일'],['reason','직접 확인한 이의 이유']])input(optional,k,label,form[k],v=>form[k]=v,k==='reason');group.append(optional);host.append(group,button('검토용 작성본 보기',()=>go(3),true));}}
 }
 if(stage===3){title('검토용 작성본을 준비했습니다.','확인된 내용은 채웠습니다. 미확인 항목이 남은 파일을 그대로 제출하지 마세요.');const remaining=missing(form);const panel=e('div');panel.className='panel no-print';panel.append(e('h2','제출 전에 남은 일'));const ul=e('ul');for(const t of [...(remaining.length?['입력 확인: '+remaining.join(' · ')]:[]),'실제 송달일·제출기한·이의 범위를 확인하세요.','법원 공식 양식·제출처와 대조하고 서명·접수 방법을 확인하세요.'])ul.append(e('li',t));panel.append(ul,button('입력 내용 보완하기',()=>go(2)));host.append(panel);const doc=e('details');doc.id='result-document';doc.append(e('summary','채워진 작성본 펼쳐보기'));const pre=e('pre',documentText(form));pre.id='draft-preview';doc.append(pre);host.append(doc);const label=e('label');label.className='check no-print';const check=e('input');check.type='checkbox';check.id='download-check';label.append(check,document.createTextNode('작성본을 대조했고, 남은 확인 사항을 이해했습니다.'));const actions=e('div');actions.className='actions no-print';const save=button('검토용 작성본 내려받기',()=>{if(!check.checked)return;const url=URL.createObjectURL(new Blob([documentHTML(form)],{type:'text/html;charset=utf-8'}));const a=e('a');a.href=url;a.download='지급명령_검토용작성본.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);},true);const print=button('인쇄 / PDF 저장',()=>{if(!check.checked)return;const was=doc.open;doc.open=true;window.addEventListener('afterprint',()=>doc.open=was,{once:true});window.print();});save.disabled=print.disabled=true;check.onchange=()=>save.disabled=print.disabled=!check.checked;actions.append(save,print);host.append(label,actions);const hint=e('p','HTML 파일로 내려받습니다. 파일은 브라우저로 열 수 있으며 입력한 개인정보가 포함될 수 있습니다.');hint.className='hint no-print';host.append(hint);}
}
$('back').onclick=()=>{cancel();go(stage===4?(story.intake?1:-1):Math.max(-1,stage-1));};$('reset').onclick=()=>{if(!source&&!busy&&!story.events[0].text&&!story.goal&&!story.intake||confirm('입력한 내용을 지울까요? 내려받은 파일은 지워지지 않습니다.')){cancel();source='';values={};candidates={};form=seed();role=goal='';story=blank();resumeReview=false;go(-1);}};
history.replaceState({simple:stage},'',location.href);window.addEventListener('popstate',event=>{cancel();go(Number.isInteger(event.state?.simple)?Math.max(-1,Math.min(event.state.simple,6)):-1,false);});window.addEventListener('pagehide',()=>{cancel();source='';values={};candidates={};form=seed();role=goal='';story=blank();stage=-1;render();});render();
